### ISSUE TITLE
Width of input smaller than desired

### ISSUE THREAD

**Issue by mrsegen** [wenzhixin/bootstrap-show-password#22]
When I added this to my login page, the password field shrunk in width.

See password field in contrast to the username field in this [jsFiddle](http://jsfiddle.net/z5exxymx/1/).

Also, there is an additional button on the right.

Does this have to do with both the `id="password"` and `name = "password"` being flagged as matches?

**Comment by unlimitedbacon** [comment]
I am having the same issue.

**Comment by Bencool** [comment]
Same issue here, any suggestion to fixed please?

**Comment by wenzhixin** [comment]
You don't need to use `data-toggle="password"` and `$el. password()` together: http://jsfiddle.net/z5exxymx/3/ or http://jsfiddle.net/z5exxymx/4/.
