### ISSUE TITLE
size of password filed becoming half 

### ISSUE THREAD

**Issue by varun4github** [wenzhixin/bootstrap-show-password#27]
Hello Team , 

I am using this this script along with input-group-addon , but by using the bootstrap-show-password the password filed is becoming half of the size it should be . And this is happening only on chrome desktop only. Working fine on Firefox and chrome mobile . 
Attached the screenshot . 
![show-hide](https://user-images.githubusercontent.com/15215930/33601386-149b197e-d9d2-11e7-8c4d-f6c86fdb0125.PNG)

**Comment by dfrostpl** [comment]
@varun4github 
can you attach your html and css? basically the easiest way is to assign custom class with width property.

**Comment by wenzhixin** [comment]
I think this problem was fixed in the latest version. Close this issue, if the problem exists reopen it and provide an example, thanks!
