### ISSUE TITLE
Update cdnsj with newest version

### ISSUE THREAD

**Issue by johnabela** [wenzhixin/bootstrap-show-password#28]
https://cdnjs.com/libraries/bootstrap-show-password

currently has ver 1.0.3 yet the latest version _(at this time is)_ 1.1.0

**Comment by wenzhixin** [comment]
Added 1.1.0 and 1.1.1 version releases: https://github.com/wenzhixin/bootstrap-show-password/releases

**Comment by wenzhixin** [comment]
Waiting for https://github.com/cdnjs/cdnjs/pulls auto update and merge the version.

**Comment by johnabela** [comment]
Looks like it has been updated. Thanks!
