### ISSUE TITLE
Improve to set maxlength

### ISSUE THREAD

**Issue by juninhograo** [wenzhixin/bootstrap-show-password#30]
Hi man,

I would like to recommend to change this part of the code:
 this.$text = $('<input type="text" />')
            [placementFuc](this.$element)
            .attr('class', this.$element.attr('class'))
            .attr('style', this.$element.attr('style'))
            .attr('placeholder', this.$element.attr('placeholder'))
            .css('display', this.$element.css('display'))
            .val(this.$element.val()).hide();

for this

 this.$text = $('<input type="text" />')
            [placementFuc](this.$element)
            .attr('class', this.$element.attr('class'))
            .attr('maxlength', this.$element.attr('maxlength'))
            .attr('style', this.$element.attr('style'))
            .attr('placeholder', this.$element.attr('placeholder'))
            .css('display', this.$element.css('display'))
            .val(this.$element.val()).hide();

Then you can improve your project to set maxlength. In this point we can use anymore html properties.

Best

**Comment by wenzhixin** [comment]
Fixed in #40
