### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by ahamana** [wenzhixin/bootstrap-show-password#32]
I have a question.
Do you have a plan to develop/support one for Bootstrap 4?

**Comment by FiloSpaTeam** [comment]
I created a fork for B4. Check here:
https://github.com/UnitooTeam/bootstrap-show-password at branch b4

**Comment by ahamana** [comment]
@FiloSpaTeam Many thanks for your contributions. Do you have a plan to support Font Awesome v5?

**Comment by FiloSpaTeam** [comment]
I ll do because i use only fa5 lol at the moment i m using data-attributes :)

**Comment by ahamana** [comment]
@FiloSpaTeam Great :clap:

**Comment by FiloSpaTeam** [comment]
See my repo at branch b4. If it's ok :+1:

**Comment by mageho** [comment]
@FiloSpaTeam Thank you for the fork.
implemented with #30 !
Cheers,
Ilan

**Comment by mageho** [comment]
Seems problem exist when you click on reveal password, the icon did not update properly.

You need to find for the data-fa-i2svg.

Line 119 : 
```
        if (this.options.eyeClassPositionInside) {
            this.$icon.find('[data-fa-i2svg]')
                .removeClass('icon-eye-open')
                .addClass('icon-eye-close')
                .html(this.options.eyeCloseClass);
        } else {
            this.$icon.find('[data-fa-i2svg]')
                .removeClass('icon-eye-open ' + this.options.eyeOpenClass)
                .addClass('icon-eye-close ' + this.options.eyeCloseClass);
        }
```

Tell me what you think.

**Comment by FiloSpaTeam** [comment]
Ehi guys, i will check asap ;)

**Comment by FiloSpaTeam** [comment]
Implemented #30 
and fixed for use with Gulp 4.0.0 :+1:

**Comment by mageho** [comment]
Cool, thank you.

**Comment by wenzhixin** [comment]
@FiloSpaTeam Any Pull Request is welcome, thanks!

**Comment by crmpicco** [comment]
Any news on this getting into the main project? @FiloSpaTeam 's fork works great with Bootstrap 4, but it would be great to get that functionality into the original project as the fork is unavailable via Yarn.

**Comment by wenzhixin** [comment]
Added PR: #40
