### ISSUE TITLE
Support for SVG of Font Awesome which uses JavaScript

### ISSUE THREAD

**Issue by ahamana** [wenzhixin/bootstrap-show-password#42]
Do you have a plan to support for SVG of Font Awesome which uses JavaScript(*)?
*: https://use.fontawesome.com/releases/v5.8.2/js/all.js
This is related to #31.

**Comment by wenzhixin** [comment]
OK, consider supporting this feature.

**Comment by wenzhixin** [comment]
http://bootstrap-show-password.wenzhixin.net.cn/examples/#size.html

**Comment by ahamana** [comment]
@wenzhixin Many thanks for your quick action!
