### ISSUE TITLE
Bootstrap version not being recognized

### ISSUE THREAD

**Issue by jpalmieri** [wenzhixin/bootstrap-show-password#47]
I'm using Bootstrap 3 (via https://github.com/seyhunak/twitter-bootstrap-rails v3.2.2). The `$.fn.dropdown.Constructor.VERSION` is `undefined`, so the library is defaulting to Bootstrap v4. What do you suggest in this case, @wenzhixin? Upgrading the app to Bootstrap 4 is not currently an option.

**Comment by wenzhixin** [comment]
I think we can set the default to v3 if the `VERSION` is `undefined`.

**Comment by wenzhixin** [comment]
I cannot found bootstrap v3.2.2, tested in v3.1.1.
