### ISSUE TITLE
html 5 validation removed

### ISSUE THREAD

**Issue by david-whitehead-uni** [wenzhixin/bootstrap-show-password#9]
Hi,

on default use of the plugin, if you have setup the fields to use 'required' as html5 and you toggle to see the password the html5 'required' validation vanishes on show password effect.

**Comment by lilpug** [comment]
Quick update,

it looks like in your toggle method or init method you should check if the required attribute is present, and add it to your generic input textbox you create. If I manually put the required field on the input textbox which becomes active once you toggle to see the password it works as it should do :).

**Comment by lilpug** [comment]
haha solved my issue, its quite simple really:-

        // Copy readonly attribute if it's set
        if (this.$element.prop('readonly'))
            this.$text.prop('readonly', true);

        //Add this bit
        if (this.$element.prop("required"))
            this.$text.prop('required', true);

**Comment by lilpug** [comment]
additional note, you will also need to remove the required field on toggle function for the one you are hiding as otherwise form validation can be an issue because you have a required field but one is hidden

**Comment by lilpug** [comment]
haha I have posted a lot on this subject, I have finally come up with a better workaround as the other one causes issues which I have mentioned above.

Add the following extra code

Show function:

        if (this.$element.prop("required"))
        {
            this.$element.prop('required', false);
            this.$text.prop('required', true);
        }

Hide function:-

        if (this.$text.prop("required")) {
            this.$element.prop('required', true);
            this.$text.prop('required', false);
        }

**Comment by wenzhixin** [comment]
Hi @lilpug , thanks for your advice, can you send me a pull request?

**Comment by wenzhixin** [comment]
Added in the latest version.
